name: smr
channels:
  - conda-forge
  - defaults
dependencies:
  - plotly
  - ruff
  - notebook
  - matplotlib
  - python
  - black
  - ipykernel
  - numpy
  - nb_conda_kernels
  - openpyxl
  - lxml
  - pandas
  - scipy